version: "2"
services:
  nodejs-api:
    build: .
    container_name: nodejs_api
    environment:
      - MONGO_URI=${MONGO_URI}
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
