version: "2"
services:
  nodejs-api:
    build: .
    container_name: nodejs_api
    environment:
      - DB_URI=${DB_URI}
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "54312:54312"
