#!/usr/bin/env node
const program = require('commander');
const app = require('./src/config/express');

program
  .version('0.0.1')
  .option('-r, --routes', 'List of all routes in the system')
  .parse(process.argv);

/**
 * Output some useful
 */
if (program.routes) {
  const displayRoutes = require('express-routemap');
  displayRoutes(app);
}
